'use client';

import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Sparkles, Download, FileText, CheckCircle2, AlertCircle } from 'lucide-react';

interface Props {
  markdown: string;
  clientName: string;
  accountType: string;
  isMismatch: boolean;
}

export function BedrockDossierViewer({ markdown, clientName, accountType, isMismatch }: Props) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="bg-slate-900 border border-slate-700/90 rounded-2xl flex flex-col h-full overflow-hidden shadow-2xl">
      {/* Dossier Header */}
      <div className="bg-slate-800/90 border-b border-slate-700 px-5 py-3.5 flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-cyan-500/20 border border-cyan-500/30 flex items-center justify-center text-cyan-400">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-bold text-white tracking-tight">AI Compliance Dossier (Synthesized PDF View)</h2>
              <span className="text-[10px] bg-cyan-950 text-cyan-300 border border-cyan-700 px-2 py-0.5 rounded-full font-semibold">
                AWS Bedrock &bull; Claude 3
              </span>
            </div>
            <p className="text-[11px] text-slate-400">Automated extraction from competitor statements &amp; state IDs</p>
          </div>
        </div>

        <button
          onClick={handlePrint}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-700/80 hover:bg-slate-600 text-xs font-medium text-slate-200 border border-slate-600 transition-colors"
        >
          <Download className="w-3.5 h-3.5 text-cyan-400" />
          <span>Export PDF</span>
        </button>
      </div>

      {/* Embedded Document Sheet Canvas */}
      <div className="flex-1 overflow-y-auto p-6 bg-slate-950/70">
        <div className="max-w-3xl mx-auto bg-white text-slate-900 rounded-xl p-8 shadow-xl font-sans border border-slate-300 text-sm leading-relaxed">
          {/* Dossier Header Banner */}
          <div className="border-b-2 border-slate-800 pb-4 mb-6 flex items-start justify-between">
            <div>
              <div className="flex items-center gap-2">
                <span className="font-extrabold text-xl tracking-tight text-slate-900">REG<span className="text-cyan-600">SHIELD</span></span>
                <span className="text-xs bg-slate-100 text-slate-700 font-semibold px-2 py-0.5 rounded border border-slate-300">
                  COMPLIANCE DOSSIER
                </span>
              </div>
              <p className="text-xs text-slate-500 mt-1">LPL Financial Back-Office Automated Clearance Report</p>
            </div>

            <div className="text-right">
              <span className={`inline-flex items-center gap-1 text-xs font-bold px-2.5 py-1 rounded-full ${
                isMismatch ? 'bg-amber-100 text-amber-800 border border-amber-300' : 'bg-emerald-100 text-emerald-800 border border-emerald-300'
              }`}>
                {isMismatch ? '⚠️ ACTION REQUIRED' : '✅ FAST-TRACK VERIFIED'}
              </span>
              <p className="text-[10px] text-slate-400 mt-1">Ref ID: {clientName.replace(/\s+/g, '-').toLowerCase()}</p>
            </div>
          </div>

          {/* Markdown Body */}
          <div className="prose prose-slate max-w-none text-slate-800 prose-headings:text-slate-900 prose-headings:font-bold prose-h1:text-lg prose-h2:text-base prose-h3:text-sm prose-table:text-xs prose-th:bg-slate-100 prose-th:p-2 prose-td:p-2 prose-td:border prose-th:border prose-table:border-collapse prose-table:w-full prose-table:my-4">
            <ReactMarkdown>{markdown}</ReactMarkdown>
          </div>

          {/* Signoff Stamp Footer */}
          <div className="mt-8 pt-4 border-t border-slate-200 flex items-center justify-between text-xs text-slate-500">
            <div>
              <p>Generated by <strong>Amazon Bedrock Compliance Pipeline</strong></p>
              <p className="text-[10px] text-slate-400">Strictly confidential &bull; Supervised machine inference</p>
            </div>
            <div className="text-right">
              <span className="font-mono text-[10px] text-slate-400">DOC-HASH: 8F9C-21A-LPL</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
