import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { v4 as uuidv4 } from 'uuid';
import { S3Service } from '../aws-s3/s3.service';
import { BedrockService } from '../aws-bedrock/bedrock.service';
import { ClientEntity, ReviewEntity, DocumentMetadata } from './domain/entities/client.entity';
import { ComplianceStatus, OnboardingStatus } from './domain/value-objects/status.vo';
import { CreateClientSubmissionDto, DecisionDto, RemediationRequestDto } from './dto/upload-request.dto';

@Injectable()
export class ComplianceService {
  private readonly logger = new Logger(ComplianceService.name);

  private clients: Map<string, ClientEntity> = new Map();
  private reviews: Map<string, ReviewEntity> = new Map();

  constructor(
    private readonly s3Service: S3Service,
    private readonly bedrockService: BedrockService
  ) {
    this.seedInitialData();
  }

  private seedInitialData() {
    const sampleId1 = 'demo-client-john-doe';
    const client1: ClientEntity = {
      id: sampleId1,
      fullName: 'Johnathan Doe',
      email: 'john.doe@californiawealth.com',
      phone: '+1 (555) 234-5678',
      dateOfBirth: '1976-08-14',
      ssnLast4: '8821',
      citizenshipStatus: 'US Citizen',
      residentialAddress: '450 Newport Center Dr, Newport Beach, CA 92660',
      accountType: 'Individual',
      targetPortfolio: 'Growth & Income (60/40 Equity/Fixed)',
      estimatedAum: 1250000,
      annualIncome: '$250,000 - $500,000',
      liquidNetWorth: '$1,000,000 - $5,000,000',
      riskTolerance: 'Moderate Growth',
      investmentObjective: 'Long-term Capital Appreciation & Tax-Advantaged Income',
      liquidityTimeHorizon: '7 - 10 Years',
      sourceOfWealth: 'Executive Compensation & Investment Liquidity',
      transferringCustodian: 'Merrill Lynch Wealth Management',
      trustedContactName: 'Mary Doe',
      trustedContactPhone: '+1 (555) 234-9988',
      trustedContactRelationship: 'Spouse',
      formCrsAcknowledged: true,
      advPart2Delivered: true,
      privacyPolicyConsent: true,
      advisorName: 'Sarah Jenkins, CFP',
      advisorFirm: 'Apex Wealth Advisory',
      advisorCrd: 'CRD# 6842109',
      notes: 'Transitioning retirement assets from Merrill Lynch. Fast-track requested.',
      documents: [
        {
          id: 'doc-1',
          originalName: 'Client_Intake_Verification_Form.pdf',
          mimeType: 'application/pdf',
          size: 245000,
          uploadedAt: new Date(Date.now() - 3600000 * 2),
        },
      ],
      createdAt: new Date(Date.now() - 3600000 * 2),
      updatedAt: new Date(Date.now() - 3600000 * 2),
    };

    const review1: ReviewEntity = {
      id: 'rev-1',
      clientId: sampleId1,
      overallStatus: ComplianceStatus.GREEN,
      onboardingStatus: OnboardingStatus.PENDING_REVIEW,
      registrationMismatch: false,
      registrationDetails: 'Structured form intake matches all regulatory suitability benchmarks.',
      portfolioRiskSummary: 'Transitioning $1.25M into Growth & Income strategy. Suitability envelope verified.',
      sourceOfFundsSummary: 'Liquid funds originating from Merrill Lynch ACAT transfer.',
      bucketScores: [
        {
          bucket: 'AML_IDENTITY',
          title: 'Bucket A: Identity & AML',
          status: ComplianceStatus.GREEN,
          summary: 'CIP verification complete. SSN, DOB, and residential address verified with 0 OFAC hits.',
          findings: ['US Citizen status confirmed.', 'Identity CIP Score: 99/100.', 'OFAC & PEP screening: Clear.']
        },
        {
          bucket: 'REG_BI_SUITABILITY',
          title: 'Bucket B: Reg BI & Suitability',
          status: ComplianceStatus.GREEN,
          summary: 'Individual ownership registration validated. Moderate risk tolerance aligns with 60/40 blend.',
          findings: ['Annual Income ($250k+) and Liquid Net Worth ($1M+) confirm suitability.', 'Estimated fee savings: 38 bps vs retail broker.']
        },
        {
          bucket: 'REQUIRED_DISCLOSURES',
          title: 'Bucket C: Required Disclosures',
          status: ComplianceStatus.GREEN,
          summary: 'Form CRS and ADV Part 2 electronic sign-offs complete with timestamp.',
          findings: ['Form CRS Relationship Summary acknowledged.', 'Fee schedule disclosed under SEC Rule 17a-14.']
        },
        {
          bucket: 'VULNERABLE_ADULT',
          title: 'Bucket D: Vulnerable Adult Protection',
          status: ComplianceStatus.GREEN,
          summary: 'Client age 48. Trusted Contact Person recorded on master profile.',
          findings: ['Trusted Contact designated: Mary Doe (Spouse).', 'FINRA Rule 2165 authorization granted.']
        }
      ],
      flaggedAnomalies: [],
      dossierMarkdown: `# RegShield Compliance Synthesis Dossier
**Generated by AWS Bedrock AI Compliance Engine (Claude 3 Sonnet)**  
**Intake Mode:** Structured Advisor Compliance Portal  
**Client:** Johnathan Doe | **Account Type:** Individual Taxable  
**Advisor:** Sarah Jenkins, CFP (Apex Wealth Advisory &bull; CRD# 6842109)  

---

### 1. Executive Compliance Audit Summary
- **Overall Determination:** **✅ CLEARED FOR IMMEDIATE APPROVAL**
- **Synthetic Suitability Score:** 99 / 100
- **Source Custodian:** Merrill Lynch Wealth Management
- **Intake Asset Volume:** **$1,250,000.00**

---

### 2. Structured Intake Form Audit Grid
| Form Section | Data Provided | Regulatory Standard | Audit Result |
| :--- | :--- | :--- | :--- |
| **Legal Identity & CIP** | Johnathan Doe (DOB: 1976-08-14) | USA PATRIOT Act / CIP | ✅ VERIFIED |
| **Tax ID / SSN** | ***-**-8821 | IRS TIN / LexisNexis | ✅ VERIFIED |
| **Account Tenancy** | Individual Taxable | FINRA Rule 4512 | ✅ CONFIRMED |
| **Suitability & Reg BI** | Moderate Growth / 60-40 Equity-Fixed | SEC Reg BI / FINRA 2111 | ✅ COMPLIANT |
| **Form CRS Acknowledgment** | Signed Electronically | SEC Form CRS Rule 17a-14 | ✅ VERIFIED |
| **Trusted Contact (TCP)** | Mary Doe (Spouse) | FINRA Rule 2165 | ✅ SATISFIED |

---

### 3. Reg BI Suitability & Risk Analysis
- **Proposed Allocation:** Growth & Income (60/40 Equity/Fixed)
- **Risk Capacity:** Annual Income ($250,000 - $500,000) and Liquid Net Worth ($1,000,000 - $5,000,000) substantiate investment profile.
- **Liquidity Horizon:** 7 - 10 Years allows for core advisory model positioning with projected **38 bps** fee reduction.

---
*Ready for 1-Click Fast-Track Back-Office Approval.*
`,
      createdAt: new Date(Date.now() - 3600000 * 2),
      updatedAt: new Date(Date.now() - 3600000 * 2),
    };

    const sampleId2 = 'demo-client-eleanor-vance';
    const client2: ClientEntity = {
      id: sampleId2,
      fullName: 'Eleanor Vance',
      email: 'eleanor.vance@example.org',
      phone: '+1 (555) 891-2345',
      dateOfBirth: '1952-03-22',
      ssnLast4: '3419',
      citizenshipStatus: 'US Citizen',
      residentialAddress: '120 Ocean View Ave, Carmel, CA 93921',
      accountType: 'Joint',
      targetPortfolio: 'Capital Preservation & Dividend Income',
      estimatedAum: 875000,
      annualIncome: '$100,000 - $250,000',
      liquidNetWorth: '$1,000,000 - $5,000,000',
      riskTolerance: 'Conservative / Income',
      investmentObjective: 'Capital Preservation & Current Income',
      liquidityTimeHorizon: '3 - 5 Years',
      sourceOfWealth: 'Retirement Assets',
      transferringCustodian: 'Charles Schwab & Co.',
      trustedContactName: '',
      formCrsAcknowledged: true,
      advPart2Delivered: true,
      privacyPolicyConsent: true,
      advisorName: 'Marcus Reynolds',
      advisorFirm: 'Pacific Horizon Financial',
      advisorCrd: 'CRD# 5129840',
      notes: 'Demo test case: Joint account selected without co-owner details & Senior investor TCP missing.',
      documents: [],
      createdAt: new Date(Date.now() - 3600000 * 5),
      updatedAt: new Date(Date.now() - 3600000 * 5),
    };

    const review2: ReviewEntity = {
      id: 'rev-2',
      clientId: sampleId2,
      overallStatus: ComplianceStatus.YELLOW,
      onboardingStatus: OnboardingStatus.ACTION_REQUIRED,
      registrationMismatch: true,
      registrationDetails: 'Form intake specifies Joint Account, but co-owner identification was omitted.',
      portfolioRiskSummary: 'Conservative portfolio strategy appropriate for client horizon.',
      sourceOfFundsSummary: 'Charles Schwab ACAT transfer.',
      bucketScores: [
        {
          bucket: 'AML_IDENTITY',
          title: 'Bucket A: Identity & AML',
          status: ComplianceStatus.GREEN,
          summary: 'Primary applicant CIP validated. 0 OFAC sanctions hits.',
          findings: ['Primary SSN verified.', 'Clear OFAC and watch list record.']
        },
        {
          bucket: 'REG_BI_SUITABILITY',
          title: 'Bucket B: Reg BI & Suitability',
          status: ComplianceStatus.YELLOW,
          summary: 'Joint tenancy selected but secondary co-owner information missing.',
          findings: ['Co-owner legal name and SSN required for Joint WROS account.']
        },
        {
          bucket: 'REQUIRED_DISCLOSURES',
          title: 'Bucket C: Required Disclosures',
          status: ComplianceStatus.GREEN,
          summary: 'Disclosures completed.',
          findings: ['Form CRS signed on March 15.']
        },
        {
          bucket: 'VULNERABLE_ADULT',
          title: 'Bucket D: Vulnerable Adult Protection',
          status: ComplianceStatus.YELLOW,
          summary: 'Client age 72 (Senior Investor). Trusted Contact Person designation is required.',
          findings: ['FINRA Rule 2165 prompt active for senior account holder.']
        }
      ],
      flaggedAnomalies: [
        'Registration Mismatch: Joint Tenancy selected on intake form, but co-owner information was omitted.',
        'Senior Investor Protection: Age 72 requires Trusted Contact Person (TCP) form.'
      ],
      dossierMarkdown: `# RegShield Compliance Synthesis Dossier
**Generated by AWS Bedrock AI Compliance Engine (Claude 3 Sonnet)**  
**Intake Mode:** Structured Advisor Compliance Portal  
**Client:** Eleanor Vance | **Account Type:** Joint (WROS)  
**Advisor:** Marcus Reynolds (Pacific Horizon Financial &bull; CRD# 5129840)  

---

### 1. Executive Compliance Audit Summary
- **Overall Determination:** **⚠️ ACTION REQUIRED / CLARIFICATION PENDING**
- **Synthetic Suitability Score:** 82 / 100
- **Source Custodian:** Charles Schwab & Co.
- **Intake Asset Volume:** **$875,000.00**

---

### 2. Structured Intake Form Audit Grid
| Form Section | Data Provided | Regulatory Standard | Audit Result |
| :--- | :--- | :--- | :--- |
| **Legal Identity & CIP** | Eleanor Vance (DOB: 1952-03-22) | USA PATRIOT Act / CIP | ✅ VERIFIED |
| **Account Tenancy** | Joint Account | FINRA Rule 4512 | ⚠️ **CO-OWNER INFO MISSING** |
| **Senior Protection** | Age 72 | FINRA Rule 2165 | ⚠️ **TRUSTED CONTACT REQUIRED** |
| **Form CRS** | Signed Electronically | SEC Form CRS Rule 17a-14 | ✅ VERIFIED |

---

### 3. Action Center Recommendation
- Dispatch automated clarification to advisor Marcus Reynolds requesting co-owner signature authorization and Trusted Contact designation.
`,
      createdAt: new Date(Date.now() - 3600000 * 5),
      updatedAt: new Date(Date.now() - 3600000 * 5),
    };

    this.clients.set(sampleId1, client1);
    this.reviews.set(sampleId1, review1);

    this.clients.set(sampleId2, client2);
    this.reviews.set(sampleId2, review2);
  }

  async getAllClientsWithReviews(): Promise<Array<{ client: ClientEntity; review: ReviewEntity }>> {
    const list: Array<{ client: ClientEntity; review: ReviewEntity }> = [];
    for (const [id, client] of this.clients.entries()) {
      const review = this.reviews.get(id);
      if (review) {
        list.push({ client, review });
      }
    }
    return list.sort((a, b) => b.client.createdAt.getTime() - a.client.createdAt.getTime());
  }

  async getClientDetails(clientId: string): Promise<{ client: ClientEntity; review: ReviewEntity }> {
    const client = this.clients.get(clientId);
    const review = this.reviews.get(clientId);
    if (!client || !review) {
      throw new NotFoundException(`Client onboarding case ${clientId} not found.`);
    }
    return { client, review };
  }

  async createSubmission(
    dto: CreateClientSubmissionDto,
    files: Express.Multer.File[] = []
  ): Promise<{ client: ClientEntity; review: ReviewEntity }> {
    const clientId = `client-${Date.now()}`;
    const uploadedDocs: DocumentMetadata[] = [];
    const extractedTexts: Array<{ fileName: string; text: string }> = [];

    if (files && files.length > 0) {
      for (const file of files) {
        const docId = `doc-${uuidv4().substring(0, 8)}`;
        const uploadResult = await this.s3Service.uploadFile(file, `clients/${clientId}`);

        uploadedDocs.push({
          id: docId,
          originalName: file.originalname,
          mimeType: file.mimetype,
          size: file.size,
          s3Key: uploadResult.key,
          s3Url: uploadResult.url,
          uploadedAt: new Date(),
        });

        extractedTexts.push({
          fileName: file.originalname,
          text: file.buffer ? file.buffer.toString('utf-8').slice(0, 5000) : '',
        });
      }
    }

    const client: ClientEntity = {
      id: clientId,
      fullName: dto.fullName,
      email: dto.email,
      phone: dto.phone,
      dateOfBirth: dto.dateOfBirth,
      ssnLast4: dto.ssnLast4,
      citizenshipStatus: dto.citizenshipStatus || 'US Citizen',
      residentialAddress: dto.residentialAddress,
      accountType: dto.accountType,
      coOwnerFullName: dto.coOwnerFullName,
      coOwnerRelationship: dto.coOwnerRelationship,
      trustName: dto.trustName,
      trustDate: dto.trustDate,
      targetPortfolio: dto.targetPortfolio,
      estimatedAum: dto.estimatedAum ? Number(dto.estimatedAum) : 750000,
      annualIncome: dto.annualIncome,
      liquidNetWorth: dto.liquidNetWorth,
      riskTolerance: dto.riskTolerance,
      investmentObjective: dto.investmentObjective,
      liquidityTimeHorizon: dto.liquidityTimeHorizon,
      sourceOfWealth: dto.sourceOfWealth,
      transferringCustodian: dto.transferringCustodian,
      trustedContactName: dto.trustedContactName,
      trustedContactPhone: dto.trustedContactPhone,
      trustedContactRelationship: dto.trustedContactRelationship,
      formCrsAcknowledged: dto.formCrsAcknowledged !== false,
      advPart2Delivered: dto.advPart2Delivered !== false,
      privacyPolicyConsent: dto.privacyPolicyConsent !== false,
      advisorName: dto.advisorName,
      advisorFirm: dto.advisorFirm || 'Independent Registered Advisor',
      advisorCrd: dto.advisorCrd || 'CRD# 7421890',
      notes: dto.notes,
      documents: uploadedDocs,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    const bedrockResult = await this.bedrockService.analyzeSubmission(client, extractedTexts);

    const initialOnboardingStatus =
      bedrockResult.overallStatus === ComplianceStatus.RED || bedrockResult.overallStatus === ComplianceStatus.YELLOW
        ? OnboardingStatus.ACTION_REQUIRED
        : OnboardingStatus.PENDING_REVIEW;

    const review: ReviewEntity = {
      id: `rev-${uuidv4().substring(0, 8)}`,
      clientId,
      overallStatus: bedrockResult.overallStatus,
      onboardingStatus: initialOnboardingStatus,
      registrationMismatch: bedrockResult.registrationMismatch,
      registrationDetails: bedrockResult.registrationDetails,
      portfolioRiskSummary: bedrockResult.portfolioRiskSummary,
      sourceOfFundsSummary: bedrockResult.sourceOfFundsSummary,
      dossierMarkdown: bedrockResult.dossierMarkdown,
      bucketScores: bedrockResult.bucketScores,
      flaggedAnomalies: bedrockResult.flaggedAnomalies,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    this.clients.set(clientId, client);
    this.reviews.set(clientId, review);

    return { client, review };
  }

  async updateDecision(clientId: string, dto: DecisionDto): Promise<ReviewEntity> {
    const review = this.reviews.get(clientId);
    if (!review) {
      throw new NotFoundException(`Review for client ${clientId} not found.`);
    }

    if (dto.action === 'Cleared to Fund') {
      review.onboardingStatus = OnboardingStatus.CLEARED_TO_FUND;
      review.overallStatus = ComplianceStatus.GREEN;
    } else if (dto.action === 'Action Required') {
      review.onboardingStatus = OnboardingStatus.ACTION_REQUIRED;
      review.overallStatus = ComplianceStatus.YELLOW;
    } else {
      review.onboardingStatus = OnboardingStatus.REJECTED;
      review.overallStatus = ComplianceStatus.RED;
    }

    review.reviewedBy = dto.reviewerName || 'LPL Compliance Principal';
    review.reviewedAt = new Date();
    review.updatedAt = new Date();

    if (dto.reviewerNotes) {
      if (!review.remediationNotes) review.remediationNotes = [];
      review.remediationNotes.push(`[${new Date().toLocaleTimeString()}] Note: ${dto.reviewerNotes}`);
    }

    return review;
  }

  async triggerRemediation(clientId: string, dto: RemediationRequestDto): Promise<{ success: boolean; message: string }> {
    const client = this.clients.get(clientId);
    const review = this.reviews.get(clientId);
    if (!client || !review) {
      throw new NotFoundException(`Client ${clientId} not found.`);
    }

    const timestamp = new Date().toLocaleTimeString();
    const logEntry = `[${timestamp}] Sent ${dto.channel} to ${client.fullName} (${client.email}): "${dto.message}"`;

    if (!review.remediationNotes) {
      review.remediationNotes = [];
    }
    review.remediationNotes.push(logEntry);
    review.onboardingStatus = OnboardingStatus.ACTION_REQUIRED;
    review.updatedAt = new Date();

    return {
      success: true,
      message: `Automated ${dto.channel} notification sent to ${client.fullName} and advisor ${client.advisorName}.`,
    };
  }
}
